version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: "postgresql://symfony:symfony@database:5432/symfony"
      PHP_IDE_CONFIG: serverName=Telegram-Bot
      XDEBUG_CONFIG: remote_host=host.docker.internal max_nesting_level=250 remote_enable=1 remote_connect_back=0 var_display_max_depth=5 idekey='PHPSTORM'
    depends_on:
      - database

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_USER: symfony
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  ngrok:
    image: wernight/ngrok
    container_name: telegram-ngrok
    env_file:
      - .env
    restart: unless-stopped
    command: ngrok start --config ngrok.yaml --all --authtoken=${NGROK_TOKEN}
    ports:
      - "4040:4040"
    volumes:
      - ./ngrok.yaml:/ngrok.yaml

volumes:
  database_data:
