version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: "postgresql://symfony:symfony@db:5432/symfony"
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: symfony
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: