version: "3"

rpc:
  listen: tcp://127.0.0.1:6001
  timeout: 60s

server:
  command: "php worker.php"
  env:
    - XDEBUG_SESSION: 2
  relay: pipes

http:
  address: 0.0.0.0:8080
  pool:
    num_workers: 4
    max_jobs: 64
    debug: true

jobs:
  consume: [ "default" ]
  pipelines:
    default:
      driver: memory
      config:
        priority: 10
        prefetch: 10

reload:
  interval: 1s
  patterns: [ ".php" ]
  services:
    http:
      recursive: true
      dirs: [ "/app" ]
