parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\ValueResolver\Telegram\Bot\BotDataResolver:
        tags:
            - { name: 'controller.argument_value_resolver' }

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
