name: PHPUnit Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: pdo_pgsql, xdebug
          coverage: xdebug

      - name: Copy .env.test to .env
        run: cp .env.test .env

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader --no-interaction

      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-text --colors=never --coverage-html coverage --coverage-filter src

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/
